version: '3'

services:

# mariadb 数据库容器
  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: python
      MYSQL_DATABASE: python
      MYSQL_USER: python
      MYSQL_PASSWORD: python
    volumes:
      - ./mariadb/db-data:/var/lib/mysql
      - ./mariadb/config:/etc/mysql
    ports:
      - "3309:3306"

#  mongo 数据库容器
#  mongo:
#    image: mongo
#    volumes:
#      - ./mongo/db:/data/db
#    ports:
#      - "27018:27017"
      
# php-fpm容器(配置文件在生成镜像的时候复制)
  php:
#    image: hermsi/alpine-fpm-php     nanoninja/php-fpm    php:7.0-fpm  
    image: wodby/drupal-php:7.1-3.0.0
#    depends_on:
#      - mysql
    environment:
      TERM: xterm
      LANG: C.UTF-8
    volumes:
      - ./coderoot:/var/www/html
    ports:
      - "9100:9000"

# python-sshd 容器
  python:
    image: monelgq/php-python-sshd  
#    depends_on:
#      - mysql
#      - mongo   
    environment:
      TERM: xterm
      LANG: C.UTF-8
      ROOT_PASSWORD: python
    volumes:
      - ./coderoot:/usr/src/app
    ports:
      - "5622:22"
      
# nginx容器
  nginx:
    image: nginx
    depends_on:
      - php
    environment:
      TERM: xterm
      LANG: C.UTF-8
    volumes:
      - ./coderoot:/var/www/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/config/fastcgi_params:/etc/nginx/fastcgi_params      
    ports:
      - "8088:80"

# PhpMyAdmin 容器     
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - mysql    
#    environment:
#      PMA_HOST: mysql
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    ports:
#     - "8085:80" 
#    volumes:
#     - /sessions   

# Redis容器
#  redis:
#    image: redis:3.2
#    ports:
#      - "6380:6379" 

# sshd容器
#  sshd:
#    image: hermsi/alpine-sshd
#    environment:
#      - ROOT_PASSWORD=python     
#    ports:
#      - "5122:22" 
#    volumes:
#      - ./coderoot:/var/www/html  
#      - ./sshd/sshkey_rsa.pub:/root/.ssh/authorized_keys:ro
#      - ./sshd/sshd_config:/etc/ssh/sshd_config  
     
# 参考： 
# 本人drupalphp
# https://github.com/nanoninja/docker-nginx-php-mysql/blob/master/docker-compose.yml
# https://github.com/Hermsi1337/docker-compose/blob/master/full_php_dev_stack/docker-compose.yml #包含可用sshd容器
# https://github.com/nanoninja/docker-nginx-php-mysql
# https://github.com/wodby/docker4drupal
# https://github.com/wodby/docker4drupal/releases
# https://cloud.wodby.com/stackhub/ada51e9b-2204-45ee-8e49-a4151912a168/overview


